// AUTO-GENERATED by @hono/inertia/vite. Do not edit.
import type app from './server'

export type PageName = '_layouts/default' | 'public/home' | 'users/list' | 'users/new' | 'users/retrieve'

declare module '@hono/inertia' {
  interface InertiaPages {
    '_layouts/default': unknown
    'public/home': unknown
    'users/list': unknown
    'users/new': unknown
    'users/retrieve': unknown
  }
  interface AppRegistry {
    app: typeof app
  }
}

export type { PageProps } from '@hono/inertia'
